# Spring properties
spring:
  application:
    name: PortalStorageApi  # Service registers under this name
  security:
    username: admin
    password: openpaasta
  http:    # spring boot 1.x
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
      location: ${java.io.tmpdir}
  servlet:    # spring boot 2.x
    multipart:
      enabled: ${spring.http.multipart.enabled}
      max-file-size: ${spring.http.multipart.max-file-size}
      max-request-size: ${spring.http.multipart.max-request-size}
      location: ${spring.http.multipart.location}

# HTTP Server
server:
  port: ${PORT:2226}   # HTTP (Tomcat) port

management:     # If you set off security...
  security:
    enabled: false

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://<PORTAL_REGISTRATION_IP>:<PORTAL_REGISTRATION_PORT>/eureka/ # YOUR EUREKA SERVER API URL
      registry-fetch-interval-seconds: 5
  instance:
    hostname: ${spring.cloud.client.hostname}
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 10

objectStorage:
  swift:
    tenantName: <OBJECTSTORAGE_TENANTNAME>
    username: <OBJECTSTORAGE_USERNAME>
    password: <OBJECTSTORAGE_PASSWORD>
    authUrl: http://<OBJECTSTORAGE_IP>:<OBJECTSTORAGE_PORT>/v2.0/tokens
    authMethod: <OBJECTSTORAGE_AUTHMETHOD>
    preferredRegion: <OBJECTSTORAGE_PREFERREDREGION>
    container: <OBJECTSTORAGE_CONTAINER>
    user:
      app:
        size:
          mb: 0           # user app upload size ( 0 : unlimited )

paasta:
  portal:
    storage:
      api:
        common:
          countoflastestexception: 10

#logging:
#  level:
#    ROOT: DEBUG

#Hystrix Setting(current version not used)
#hystrix:
#  threadpool:
#    default:
#      # Maximum number of concurrent requests when using thread pools (Default: 10)
#      coreSize: 100
#      # Maximum LinkedBlockingQueue size - -1 for using SynchronousQueue (Default: -1)
#      maxQueueSize: -1
#      # Queue size rejection threshold (Default: 5)
#      queueSizeRejectionThreshold: 5
#  command:
#    default:
#      circuitBreaker:
#        sleepWindowInMilliseconds: 60000
#        requestVolumeThreshold: 3
#      execution:
#        isolation:
#          #strategy: SEMAPHORE, no thread pool but timeout handling stops to work
#          strategy: THREAD
#          thread:
#            timeoutInMilliseconds: 60000
#
